spring:
  application:
    name: todoApp
  h2:
    console.enabled: true
    datasource:
      url: jdbc:h2:mem:todoapp
      driverClassName: org.h2.Driver
      gebruikersnaam: root
      wachtwoord: password
      jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

